[package]
name = "RoseTree"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1"
chrono = "0.4"
ignore = "0.4"
dashmap = "6"
simdutf8 = "0.1"

[lints.clippy]
pedantic = { level = "warn" }

[profile.release]
lto = "fat"
